version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    groups:
      npm-prod:
        dependency-type: "production"
      npm-dev:
        dependency-type: "development"
    schedule:
      interval: "weekly"